# Generated by Django 5.2.10 on 2026-01-17 01:06

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('DEBITO', 'Débito (à vista)'), ('CREDITO', 'Crédito (a prazo)'), ('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix')], max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('exige_cartao', models.BooleanField(default=False, help_text='Se marcado, esta forma de pagamento exige cartão.')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('C', 'Crédito (Entrada)'), ('D', 'Débito (Saída)')], default='D', max_length=1)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Novo Cartão', max_length=100, verbose_name='Nome do cartão')),
                ('limite', encrypted_model_fields.fields.EncryptedDecimalField(default=0)),
                ('dia_fechamento', models.PositiveIntegerField(default=1)),
                ('is_credito', models.BooleanField(default=True, help_text='Cartão de crédito (gera débito contábil)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('is_global', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('titulo', encrypted_model_fields.fields.EncryptedCharField(max_length=200, verbose_name='Título')),
                ('valor', encrypted_model_fields.fields.EncryptedDecimalField(blank=True, null=True, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data da transação')),
                ('parcelas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Parcelas')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('observacoes', encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('grupo_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID do Grupo')),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.cartao', verbose_name='Cartão')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.categoria')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cal.formapagamento', verbose_name='Forma de pagamento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cal.tipo', verbose_name='Tipo contábil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', encrypted_model_fields.fields.EncryptedDecimalField()),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ano', 'mes', 'categoria'],
                'unique_together': {('user', 'categoria', 'mes', 'ano')},
            },
        ),
    ]
