# Generated by Django 5.2.1 on 2025-05-20 14:31

import cal.models
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do tipo')),
                ('categoria', models.CharField(max_length=200, verbose_name='Categoria')),
                ('is_credito', models.BooleanField(default=False, verbose_name='É crédito?')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('titulo', encrypted_model_fields.fields.EncryptedCharField(max_length=200, verbose_name='Título')),
                ('valor', cal.models.EncryptedDecimalField(blank=True, null=True, verbose_name='Valor total')),
                ('data', models.DateField(verbose_name='Data da transação')),
                ('parcelas', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de parcelas')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data da última parcela')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.categoria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cal.tipo', verbose_name='Tipo da transação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
