# Generated by Django 5.2.10 on 2026-07-24 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor mensal')),
                ('dia_cobranca', models.PositiveSmallIntegerField(default=1, help_text='Dia do mês em que o lançamento deve ser gerado (1-28, para evitar problemas com meses curtos).', verbose_name='Dia da cobrança')),
                ('data_inicio', models.DateField(blank=True, default=None, null=True, verbose_name='Início')),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco para repetir indefinidamente até ser desativada.', null=True, verbose_name='Repetir até')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacoes', models.CharField(blank=True, max_length=500, null=True)),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.cartao', verbose_name='Cartão')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.categoria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cal.tipo', verbose_name='Tipo contábil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recorrência',
                'verbose_name_plural': 'Recorrências',
                'ordering': ['-ativa', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='recorrencia',
            field=models.ForeignKey(blank=True, help_text='Preenchido automaticamente quando esta transação foi gerada por uma assinatura/recorrência.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_geradas', to='cal.recorrencia', verbose_name='Recorrência de origem'),
        ),
    ]
