# Generated by Django 5.2.1 on 2026-01-07 02:13

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AddField(
            model_name='transacao',
            name='observacoes',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True, verbose_name='Observações (Criptografadas)'),
        ),
    ]
