# Generated by Django 5.2.1 on 2025-05-14 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data da transação')),
                ('categoria', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('SALARIO', 'Salário'), ('EMPRESTIMO', 'Empréstimo'), ('CRIPTO', 'Criptomoeda')], max_length=20)),
                ('recorrente', models.BooleanField(default=False)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
