# Generated by Django 6.0.1 on 2026-01-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_alter_categoria_options_categoria_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
