# Generated by Django 5.2.1 on 2026-01-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_alter_cartao_options_transacao_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='adia_mes',
            field=models.BooleanField(default=False, help_text='Se marcado, transações após o fechamento vão para o mês subsequente.'),
        ),
        migrations.AddField(
            model_name='tipo',
            name='dia_fechamento',
            field=models.PositiveIntegerField(default=0, help_text='Para cartões: dia que a fatura fecha. 0 se não for cartão.'),
        ),
    ]
