# Generated by Django 5.2.10 on 2026-07-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_alter_recorrencia_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='ano',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='mes',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transacao',
            unique_together={('recorrencia', 'ano', 'mes')},
        ),
    ]
