# Generated by Django 5.2.10 on 2026-01-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_cartao_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='grupo_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID do Grupo'),
        ),
    ]
