# Generated by Django 5.2.1 on 2026-01-07 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_tipo_adia_mes_tipo_dia_fechamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='dia_fechamento',
            field=models.PositiveIntegerField(default=1, verbose_name='Dia de fechamento'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='limite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Limite do cartão'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transacao',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.cartao', verbose_name='Cartão utilizado'),
        ),
    ]
