# Generated by Django 5.2.10 on 2026-01-16 15:14

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_transacao_grupo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='limite',
            field=encrypted_model_fields.fields.EncryptedDecimalField(default=0),
        ),
        migrations.AlterField(
            model_name='metacategoria',
            name='limite',
            field=encrypted_model_fields.fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=encrypted_model_fields.fields.EncryptedDecimalField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
