# Generated by Django 5.2.10 on 2026-07-26 12:11

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_recorrencia_transacao_recorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrencia',
            name='observacoes',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recorrencia',
            name='titulo',
            field=encrypted_model_fields.fields.EncryptedCharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='recorrencia',
            name='valor',
            field=encrypted_model_fields.fields.EncryptedDecimalField(decimal_places=2, max_digits=15, verbose_name='Valor mensal'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='observacoes',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='titulo',
            field=encrypted_model_fields.fields.EncryptedCharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=encrypted_model_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor'),
        ),
    ]
