# Generated by Django 5.2.10 on 2026-07-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_add_ano_mes_unique_recorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('DEBITO', 'Débito (à vista)'), ('CREDITO', 'Crédito (a prazo)'), ('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix')], max_length=20, null=True, verbose_name='Forma de pagamento'),
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='is_credito',
        ),
        migrations.AddField(
            model_name='cartao',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Crédito (entrada no extrato do cartão = débito contábil) ou Débito', null=True, on_delete=django.db.models.deletion.PROTECT, to='cal.tipo', verbose_name='Tipo contábil'),
        ),
        migrations.DeleteModel(
            name='FormaPagamento',
        ),
    ]
